version: '3.2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: "$ELK_VERSION"
    volumes:
    - "es_data:/usr/share/elasticsearch/data"
    ports:
    - "$ES_PORT:9200"
    - "$ES_CLUSTER_PORT:9300"
    environment:
    - "ES_JAVA_OPTS:'-Xmx256m -Xms256m'"
    env_file:
    - ./.env
    networks:
    - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: "$ELK_VERSION"
        LS_INPUT_FILE: "$LS_INPUT_FILE"
    volumes:
    - "$LS_INPUT_FILE_LOCAL:$LS_INPUT_FILE"
    ports:
    - "$LS_PORT:5600"
    - "$LS_INPUT_TCP_PORT:$LS_INPUT_TCP_PORT"
    environment:
    - "LS_JAVA_OPTS:'-Xmx256m -Xms256m'"
    env_file:
    - ./.env
    networks:
    - elk
    links:
    - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: "$ELK_VERSION"
    ports:
    - "$KB_PORT:5601"
    env_file:
    - ./.env
    networks:
    - elk
    links:
    - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  es_data:
    external: false
