version: '3.2'

services:

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: "$ELK_VERSION"
        LS_LOGFILE: "$LS_LOGFILE"
    volumes:
    - "./logstash/log/temperature.log:$LS_LOGFILE"
    ports:
    - "$LS_PORT:$LS_PORT"
    - "9600:9600"
    environment:
    - "LS_JAVA_OPTS:'-Xmx256m -Xms256m'"
    - "ES_HOST=$ES_HOST"
    - "ES_PORT=$ES_PORT"
    - "LS_LOGFILE=$LS_LOGFILE"
    - "LS_PORT=$LS_PORT"
    - "LOG_LEVEL=$LOG_LEVEL"

