version: '3.2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: "$ELK_VERSION"
    volumes:
    - "es_data:/usr/share/elasticsearch/data"
    ports:
    - "$ES_PORT:$ES_PORT"
    - "$ES_CLUSTER_PORT:$ES_CLUSTER_PORT"
    environment:
    - "ES_JAVA_OPTS:'-Xmx256m -Xms256m'"
    networks:
    - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: "$ELK_VERSION"
    ports:
    - "$KB_PORT:$KB_PORT"
    networks:
    - elk
    links:
    - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  es_data:
    external: false
