version: '3.2'

services:

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: "$ELK_VERSION"
        LS_INPUT_FILE: "$LS_INPUT_FILE"
    volumes:
    - "$LS_INPUT_FILE_LOCAL:$LS_INPUT_FILE"
    ports:
    - "$LS_PORT:5600"
    - "$LS_INPUT_TCP_PORT:$LS_INPUT_TCP_PORT"
    environment:
    - "LS_JAVA_OPTS:'-Xmx256m -Xms256m'"
    env_file:
    - ./.env
    networks:
    - elk

networks:
  elk:
    driver: bridge
